# Sample .travis.yml for R projects

language: r
sudo: false
cache: packages

notifications:
  email:
    on_success: change
    on_failure: change

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'
